development:
  adapter: postgresql
  database: rs-dev
  username: remotestandup
  password: remotestandup
  host: localhost

test:
  adapter: postgresql
  database: rs-test
  username: remotestandup
  password: remotestandup
  host: localhost

production:
  adapter: postgresql
  database: rs-pro
  uri: <%= ENV['DATABASE_URL'] %>
